docs/content/_index.md, docs/content/api-reference/_index.md, docs/content/mini-protocols/local-chain-sync.md, docs/static/ogmios.wsp.json, server/CHANGELOG.md, server/src/Ogmios/App/Server/WebSocket.hs, server/src/Ogmios/Control/MonadWebSocket.hs, server/src/Ogmios/Data/Json.hs, server/src/Ogmios/Data/Json/Allegra.hs, server/src/Ogmios/Data/Json/Byron.hs, server/src/Ogmios/Data/Json/Mary.hs, server/src/Ogmios/Data/Json/Prelude.hs, server/src/Ogmios/Data/Json/Shelley.hs, server/static/tests/chain-sync.js, server/test/unit/Ogmios/Data/JsonSpec.hs
Ticket: #9 
--- 
Some preliminary results: 
<details>
<summary>Byron</summary>
**mode**: full
```json
{
"totalBlocks": 50000,
"totalTime": "5.172s",
"totalSize": "90.61MB",
"block/s": "9667",
"MB/s": "18"
}
```
**mode**: compact
```json
{
"totalBlocks": 50000,
"totalTime": "3.965s",
"totalSize": "43.89MB",
"block/s": "12610",
"MB/s": "11"
}
```
</details>
<details>
<summary>Shelley</summary>
**mode**: full
```json
{
"totalBlocks": 50000,
"totalTime": "9.259s",
"totalSize": "233.75MB",
"block/s": "5400",
"MB/s": "25"
}
```
**mode**: compact
```json
{
"totalBlocks": 50000,
"totalTime": "6.799s",
"totalSize": "117.76MB",
"block/s": "7354",
"MB/s": "17"
}
```
</details>
<details>
<summary>Allegra</summary>
**mode**: full
```json
{
"totalBlocks": 50000,
"totalTime": "9.864s",
"totalSize": …
```
=> Enable compact-mode

docs/content/getting-started/monitoring.md, server/.hlint.yaml, server/CHANGELOG.md, server/src/Ogmios/App/Health.hs, server/src/Ogmios/App/Options.hs, server/src/Ogmios/App/Protocol/ChainSync.hs, server/src/Ogmios/App/Protocol/StateQuery.hs, server/src/Ogmios/App/Server/Http.hs, server/src/Ogmios/Control/MonadSTM.hs, server/src/Ogmios/Data/Health.hs
```
[ogmios:Info:25] [2021-04-17 21:51:04.43 UTC] OgmiosHealth {healthCheck = HealthTick {status = Health {startTime = 2021-04-17 21:49:44.379862746 UTC, lastKnownTip = Tip (SlotNo 23727880) 514320620f62ecd7e75ea5de13668a5fb9f182d04aa28ffcc1e53497b0f42530 (BlockNo 2482974), lastTipUpdate = Just 2021-04-17 21:51:04.437438569 UTC, networkSynchronization = NetworkSynchronization 0.98, metrics = Metrics {runtimeStats = RuntimeStats {maxHeapSize = 240, currentHeapSize = 496, cpuTime = 6212560918, gcCpuTime = 35185618}, activeConnections = 0, totalConnections = 0, sessionDurations = DistributionStats {mean = 0.0, min = 0.0, max = 0.0}, totalMessages = 0, totalUnrouted = 0}}}}
```
```json
{
"metrics": {
"totalUnrouted": 0,
"totalMessages": 0,
"runtimeStats": {
"gcCpuTime": 61798742,
"cpuTime": …
```
=> Add network synchronization to health object 

server/package.yaml, server/src/Ogmios/App/Options.hs, server/test/unit/Ogmios/App/OptionsSpec.hs
Fixes #35 
- c69e8ce593f497b44a017d59495ffe5dc550f6de
:round_pushpin: **Allow passing slots per epochs to the network parameter env var**
- 77e30bb9d74c98e483eb36795ef634810ad911fb
:round_pushpin: **Add property test checking for 'parseNetworkParameters'**
Also reworked the command-line `--help` to provide some concrete examples of the `OGMIOS_NETWORK` env var:
```console
$ ogmios --help
Provides a bridge between cardano-node and WebSocket clients. Ogmios translates
the existing CBOR-based Ouroboros mini-protocols into JSON-WSP-based protocols,
through WebSocket channels.
Usage: ogmios ((-v|--version) | --node-socket FILEPATH [--host IPv4] 
[--port TCP/PORT] [--timeout SECONDS] [--log-level SEVERITY])
Ogmios - A JSON-WSP WebSocket adaptor for cardano-node
Available options:
-h,--help …
```
=> Allow passing slots per epochs to the network parameter env var

clients/TypeScript/README.md, clients/TypeScript/packages/client/src/ChainSync/ChainSyncClient.ts, clients/TypeScript/packages/client/src/ChainSync/index.ts, clients/TypeScript/packages/client/src/ChainSync/requestNext.ts, clients/TypeScript/packages/client/test/ChainSync.test.ts, clients/TypeScript/packages/repl/README.md, clients/TypeScript/packages/repl/src/index.ts, server/static/tests/chain-sync.js
Adds a function to handle the sync setup, including request pipelining
to optimize performance. The default is 100 requests, but it's a configurable
argument. The `ChainSyncClient` no longer exposes `findIntersect`, and the awkward
`initialIntersection` logic removed.
=> Feature: ChainSyncClient.startSync

docs/static/ogmios.wsp.json, server/CHANGELOG.md, server/modules/json-wsp/CHANGELOG.md, server/modules/json-wsp/json-wsp.cabal, server/modules/json-wsp/package.yaml, server/modules/json-wsp/src/Codec/Json/Wsp.hs, server/modules/json-wsp/src/Codec/Json/Wsp/Handler.hs, server/src/Ogmios/Data/Protocol.hs, server/src/Ogmios/Data/Protocol/ChainSync.hs, server/src/Ogmios/Data/Protocol/StateQuery.hs, server/test/unit/Ogmios/Data/JsonSpec.hs
Fixes #39 
- 7e03e905c1e297414c216009d6614034d2047adf
:round_pushpin: **Allow constructing WSP request JSON value in json-wsp**
- 7a21ba8e4029bbc4927f9eb94f08ef4eb82f5a34
:round_pushpin: **Add unit test to check JSON schema of arbitrarily generated *FindIntersect* requests**
There was responses for a while, but not requests.
- bdce31d51f3ac8af58d285e5412095b5a016723c
:round_pushpin: **Add additional test cases for 'RequestNext', 'Acquire' and 'Release'.**
It fails, as intended because of #39
- caef7de7e49a1f0e0dfad8a8e8fc949144570822
:round_pushpin: **Fix wrong schema definition for 'Acquire', now captured by automated tests.**
- 86b869a9966b47fad35e1f0d996995ff49ca4b9a
:round_pushpin: **Fill in CHANGELOG**
=> Fix 'Acquire' definition and add extra automated tests for JSON *request* schemas 

clients/TypeScript/packages/client/src/ChainSync/findIntersect.ts, clients/TypeScript/packages/client/src/StateQuery/Query.ts, clients/TypeScript/packages/client/src/StateQuery/index.ts, clients/TypeScript/packages/client/src/StateQuery/queries/currentEpoch.ts, clients/TypeScript/packages/client/src/StateQuery/queries/currentProtocolParameters.ts, clients/TypeScript/packages/client/src/StateQuery/queries/delegationsAndRewards.ts, clients/TypeScript/packages/client/src/StateQuery/queries/eraStart.ts, clients/TypeScript/packages/client/src/StateQuery/queries/genesisConfig.ts, clients/TypeScript/packages/client/src/StateQuery/queries/ledgerTip.ts, clients/TypeScript/packages/client/src/StateQuery/queries/nonMyopicMemberRewards.ts, clients/TypeScript/packages/client/src/StateQuery/queries/proposedProtocolParameters.ts, clients/TypeScript/packages/client/src/StateQuery/queries/stakeDistribution.ts, clients/TypeScript/packages/client/src/StateQuery/queries/utxo.ts, clients/TypeScript/packages/client/src/TxSubmission/submitTx.ts, clients/TypeScript/packages/client/test/StateQuery.test.ts
- adds a `Query` function to DRY up the code
- replaces self-removing event listeners, for the request-response
interactions, with manual removal of the listener after the handler
resolves.
- adds a test case to demonstrate concurrency when making state queries,
via the client.
Closes #40
=> fix: ensure short-lived message listeners are not removed prematurely

clients/TypeScript/packages/client/package.json, clients/TypeScript/packages/client/src/ChainSync/ChainSyncClient.ts, clients/TypeScript/packages/client/test/ChainSync.test.ts, clients/TypeScript/packages/repl/src/index.ts, clients/TypeScript/yarn.lock
**feature: client TypeScript chain-sync client requestNext improvement**
**BREAKING CHANGE:** ChainSyncClient no longer exposes a `requestNext`
function. Instead you must invoke the callback provided as the second
argument in each of rollBackward and rollForward handlers.
**BREAKING CHANGE:** ChainSyncClient no longer exposes JSON-WSP reflection,
as there would be unexpected results given the first n messages would all
share the same reflected value.
_____
**fix: queue client TypeScript chain-sync requestNext responses**
Implements an in-memory queue to ensure `requestNext` responses are processed
sequentially when there are async operations in the message handlers.
**BREAKING CHANGE:** The `ChainSyncClientMessageHandlers` methods now must return
a promise.
Note: The dependency introduced …
=> fix: client TypeScript chain-sync sequential processing

.github/workflows/continuous-integration.yaml, CHANGELOG.md, clients/TypeScript/packages/client/src/StateQuery/StateQueryClient.ts, clients/TypeScript/packages/client/src/StateQuery/queries/delegationsAndRewards.ts, clients/TypeScript/packages/client/src/StateQuery/queries/nonMyopicMemberRewards.ts, clients/TypeScript/packages/client/src/StateQuery/queries/utxo.ts, clients/TypeScript/packages/client/src/TxSubmission/errors.ts, clients/TypeScript/packages/client/src/TxSubmission/submitTx.ts, clients/TypeScript/packages/client/test/StateQuery.test.ts, docs/static/ogmios.wsp.json, server/modules/hspec-json-schema/CHANGELOG.md, server/modules/hspec-json-schema/src/Test/Hspec/Json/Schema.hs, server/modules/hspec-json-schema/test/Test/Hspec/Json/SchemaSpec.hs, server/ogmios.cabal, server/package.yaml, server/src/Ogmios/Data/Json/Allegra.hs, server/src/Ogmios/Data/Json/Alonzo.hs, server/src/Ogmios/Data/Json/Byron.hs, server/src/Ogmios/Data/Json/Mary.hs, server/src/Ogmios/Data/Json/Prelude.hs, server/src/Ogmios/Data/Json/Shelley.hs, server/test/golden/QueryResponse-utxo_1.json, server/test/golden/SubmitTxResponse_1.json, server/test/unit/Ogmios/Data/JsonSpec.hs
- :round_pushpin: **Cover Alonzo[Block] in the JSON-WSP specification.**
This does not yet cover the new errors coming from the transaction submission. So I don't expect the corresponding tests to pass, but the RequestNextResponse now should when enabling Alonzo generators.
- :round_pushpin: **Generate AlonzoBlock as part of the JSON test suite**
Weirdly enough, I couldn't resort to a simple 'Arbitrary' this time, because it seems that the transactions within blocks are different from the transactions generated by the arbitrary instance. So, I had to fmap on the sequence of Tx using a newly introduced 'toTxSeq'. I don't know if the tests pass since I am running some heavy simulations on the side and my laptop will just die of exhaustion if I run the test ... I knew 16GB of RAM was not …
=> Alonzo - Part 2 (JSON Schema for Alonzo data-types) 

CHANGELOG.md, clients/TypeScript/package.json, clients/TypeScript/packages/client/package.json, clients/TypeScript/packages/repl/package.json, clients/TypeScript/packages/schema/package.json, server/ogmios.cabal
Adds missing TypeScript client changelog entries and bumps version to 4.0.0-beta.1
_I decided to use `beta` to align with the previous pre-releases but forgot to rename the branch._
=> Release 4.0.0-beta.1

CHANGELOG.md, server/cabal.project, server/modules/cardano-client/cardano-client.cabal, server/modules/cardano-client/package.yaml, server/modules/cardano-client/src/Cardano/Network/Protocol/NodeToClient.hs, server/modules/cardano-client/src/Cardano/Network/Protocol/NodeToClient/Trace.hs, server/modules/json-via-show/CHANGELOG.md, server/modules/json-via-show/README.md, server/modules/json-via-show/json-via-show.cabal, server/modules/json-via-show/package.yaml, server/modules/json-via-show/src/Data/Aeson/Via/Show.hs, server/modules/json-via-show/src/Data/Aeson/Via/Show/Internal.hs, server/modules/json-via-show/test/unit/Data/Aeson/Via/ShowSpec.hs, server/ogmios.cabal, server/package.yaml, server/src/Ogmios.hs, server/src/Ogmios/App/Health.hs, server/src/Ogmios/App/Metrics.hs, server/src/Ogmios/App/Server.hs, server/src/Ogmios/App/Server/WebSocket.hs, server/src/Ogmios/Data/Json.hs, server/src/Ogmios/Data/Json/Prelude.hs, server/stack.yaml
- :round_pushpin: **Attempt to rework json-via-show**
In the end, it kinda works but it feels *very* hacky and it makes me
uncomfortable knowing that one of the critical part of the system may
rely on something which may choke and collapse at the first input.
It was a fun experiment though, and I wish that the `Show` interface
was a bit more normalized in Haskell to be actually any useful for
anything beyond simple human consumption.
- :round_pushpin: **Write JSON encoder for the 'TraceClient' wrapping the ouroboros network traces**
This is mainly for logging, not perfect but still far better than printing things via show. I've also increased the severity of the handshake traces to Info since this is actually pretty useful to have around hard-forks and, in general. Handshake traces aren't …
=> Rework JSON logs, in particular nested logs from the network layer 

Dockerfile, docs/content/getting-started/docker.md, scripts/cardano-node-ogmios.sh
- Adds a top-level `ipc` directory for the cardano-node socket
to be created in, which can be mounted for multi-container stacks.
- Documents the mount point, and improve the existing docs.
- Remove trailing spaces as per `.editorconfig`
=> feature: external Haskell node client interoperability with cardano-node-ogmios

server/modules/cardano-client/src/Cardano/Network/Protocol/NodeToClient.hs, server/modules/json-wsp/CHANGELOG.md, server/modules/json-wsp/src/Codec/Json/Wsp.hs, server/modules/json-wsp/src/Codec/Json/Wsp/Handler.hs, server/ogmios.cabal, server/package.yaml, server/src/Ogmios/App/Options.hs, server/src/Ogmios/App/Protocol.hs, server/src/Ogmios/App/Protocol/ChainSync.hs, server/src/Ogmios/App/Protocol/StateQuery.hs, server/src/Ogmios/App/Protocol/TxSubmission.hs, server/src/Ogmios/App/Server/WebSocket.hs, server/src/Ogmios/Data/Json/Prelude.hs, server/src/Ogmios/Data/Json/Query.hs, server/src/Ogmios/Data/Protocol/ChainSync.hs, server/src/Ogmios/Data/Protocol/StateQuery.hs, server/src/Ogmios/Data/Protocol/TxSubmission.hs, server/src/Ogmios/Prelude.hs, server/test/unit/Ogmios/App/Protocol/ChainSyncSpec.hs, server/test/unit/Ogmios/App/Protocol/StateQuerySpec.hs, server/test/unit/Ogmios/Data/JsonSpec.hs, server/test/unit/Test/App/Protocol/Util.hs, server/test/unit/Test/Generators.hs
- :round_pushpin: **Write unit test using io-sim for the ChainSync protocol.**
For now, it only covers basic scenario but, the instrumentation behind the scene is pretty heavy. In particular, it could (would) be used to generate a random sequence of input chain sync messages, for then we can ensure some properties like: order preservation, expected response, no deadlock / errors etc... It'd be interesting to also do it for the local state query and the health check, to make sure that all cases are properly handled by the logic. Everything runs in IO-sim, so it's blazing fast and doesn't require any real networking setup :tada:
- :round_pushpin: **Make max in flight (a.k.a. pipelined) chain-sync requests configurable**
This is mainly for enabling unit test scenarios which saturate the …
=> Unit tests for Ouroboros mini-protocols using simulated IO

docs/content/getting-started/docker.md, scripts/cardano-node-ogmios.sh
Without this change implementations would need to mount into /root/db.
=> refactor: change cardano-node-ogmios database mount point to /db

.github/workflows/continuous-integration.yaml, .github/workflows/network-synchronization.yaml
This change makes it simple for other products to implement similar workflows. The refactor is done in the first commit, then I intend to replace the local action with a Github Marketplace ref in a second commit. I did try to retain the integrity of the existing cache, [however, the node was still syncing from genesis](https://github.com/CardanoSolutions/ogmios/runs/2928087529?check_suite_focus=true) so I elected to make the cache directory changes to better align with the Docker run requirements, and good practice of writing to the runner's temp directory.
- Replaces the multi-container implementation with cardano-node-ogmios.
- Uses temp directory on runner
```
Cache not found for input keys: cardano-node-testnet-20210627, cardano-node-testnet
```
``` yml
push:
branches: [ …
```
=> refactor: lift node sync logic to GitHub action

.github/workflows/docker.yaml
The build action was missing the network build-args,
so the image tagged as testnet was actually the mainnet
since it's the default.
=> ci: fix network Docker builds on Docker Hub

docs/content/api-reference/_index.md, docs/content/getting-started/building.md, docs/content/typescript-client/chain-sync.md, docs/content/typescript-client/state-query.md, docs/content/typescript-client/tx-submission.md
**:pushpin: docs: Remove duplicate headings in TypeScript client docs**
Also removes illegal whitespace
**:pushpin: docs: Add client build instructions to getting started docs**
**:pushpin: Use relative links for TypeScript client and API reference docs**
@KtorZ  The last commit is untested, and probably only partially resolving the issue as it looks like the index page link structure doesn't match the hugo output. See inline comment
Closes #92 #93
=> Documentation tweaks

clients/TypeScript/package.json, clients/TypeScript/packages/client/package.json, clients/TypeScript/packages/client/src/ChainSync/ChainSyncClient.ts, clients/TypeScript/packages/client/src/ChainSync/requestNext.ts, clients/TypeScript/packages/client/src/StateQuery/Query.ts, clients/TypeScript/packages/client/src/StateQuery/StateQueryClient.ts, clients/TypeScript/packages/client/src/TxSubmission/errors.ts, clients/TypeScript/packages/client/src/errors/IntersectionNotFoundError.ts, clients/TypeScript/packages/client/src/errors/UnknownResultError.ts, clients/TypeScript/packages/client/src/util.ts, clients/TypeScript/packages/client/test/util.test.ts, clients/TypeScript/packages/schema/package.json, clients/TypeScript/yarn.lock, docs/static/ogmios.wsp.json, server/test/unit/Ogmios/Data/JsonSpec.hs
- :round_pushpin: **Use fork / temporary version of json-schema-to-typescript including the bigint fix.**
See bcherny/json-schema-to-typescript#401
- :round_pushpin: **Use json-bigint parser and serialiser with native bigint.**
```ts
[...]
export type Epoch = bigint;
export type Hash64 = string;
export type Slot = bigint;
/**
* A Cardano address (either legacy format or new format).
*/
export type Address = string;
/**
* An amount, in Lovelace (1e6 Lovelace = 1 Ada)
*/
export type Lovelace = bigint;
/**
* A number of asset, can be negative went burning assets.
*/
export type AssetQuantity = bigint;
export type DatumHash = string;
export type Null = null;
export type TxWitness = WitnessVk | RedeemWitness;
export type NullableRatio = Ratio | Null;
/**
* A ratio of two integers, to express …
```
=> Handle Large Integers via native BigInt in the TypeScript client 

CHANGELOG.md, Dockerfile, docker-compose.yml
Updates the latest node RC and config. _alonzo-qa_ and _alonzo-purple_ were re-spun on 2021-08-21
https://github.com/input-output-hk/cardano-node/compare/alonzo-purple-1.0.2...1.29.0-rc2
=> chore: bump cardano-node and config

clients/TypeScript/packages/schema/package.json
The use of the `INIT_CWD` env in the npm script is unnecessary for development,
and breaks CI. This was a carry-over from another project where context was more tricky,
although I do not recall exactly why this approach was taken.
https://github.com/CardanoSolutions/ogmios/runs/3329401416?check_suite_focus=true
=> ci: fix TypeScript schema generation in CI

clients/TypeScript/packages/client/src/StateQuery/StateQueryClient.ts, clients/TypeScript/packages/client/test/StateQuery.test.ts
- :round_pushpin: **Change state query client setup to not acquire when no point is provided.**
Behind the scene, the server will automatically acquire the most recent tip and run the query for that point. This however exposes clients to race conditions should they make multiple queries one after the other and expect them to be consistent.
- :round_pushpin: **Allow state query client to re-acquire points when necessary.**
Fixes #90
=> Re-acquire state query points

CHANGELOG.md, clients/TypeScript/packages/client/src/StateQuery/Query.ts, clients/TypeScript/packages/client/src/StateQuery/queries/delegationsAndRewards.ts, clients/TypeScript/packages/client/test/StateQuery.test.ts
Motivation: When you enter an invalid stake address to delegationsAndRewards API endpoint, the function fails on
(node:267433) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'eraMismatch' of undefined
at isEraMismatch (node_modules/@cardano-ogmios/client/src/StateQuery/queries/delegationsAndRewards.ts:16:9)
at Object.handler (node_modules/@cardano-ogmios/client/src/StateQuery/queries/delegationsAndRewards.ts:46:8)
and never finishes. This fix provides at least a rejection instead of neverending await.
=> Handle client faults in the TypeScript StateQueryClient

clients/TypeScript/.eslintrc.js, clients/TypeScript/packages/client/src/ChainSync/ChainSyncClient.ts, clients/TypeScript/packages/client/test/Connection.test.ts, clients/TypeScript/packages/client/test/ServerHealth.test.ts, clients/TypeScript/packages/client/test/StateQuery.test.ts, clients/TypeScript/packages/client/test/TxSubmission.test.ts, clients/TypeScript/packages/repl/src/index.ts
In an attempt to narrow #120 I discovered we have a few floating promises. This doesn't appear to touch the code of interest, so is unlikely to change much there, but it should improve the reliability of tests given the `delay`s were not being awaited.
=> fix: address floating promises

CHANGELOG.md, clients/TypeScript/package.json, clients/TypeScript/packages/client/src/StateQuery/StateQueryClient.ts, clients/TypeScript/packages/client/src/StateQuery/queries/delegationsAndRewards.ts, clients/TypeScript/packages/client/src/StateQuery/queries/ledgerTip.ts, clients/TypeScript/packages/client/src/StateQuery/queries/nonMyopicMemberRewards.ts, clients/TypeScript/packages/client/test/ChainSync/ChainSync.test.ts, clients/TypeScript/packages/client/test/StateQuery/StateQuery.test.ts, clients/TypeScript/packages/repl/src/index.ts, clients/TypeScript/packages/schema/src/index.ts, docs/static/ogmios.wsp.json
Fixes #139.
- :round_pushpin: **Replace 'Hash16' with more precise schema definitions.**
Some of them were actually not even hashes, but just happened to be base16-encoded strings. It's clearer that way.
- :round_pushpin: **Re-generate TypeScript schema and adjust types accordingly.**
- :round_pushpin: **Explicitly list TypeScript's workspace packages**
And in particular, make sure that 'schema' appears before 'client',
which appears before 'repl'. This is because, changing the schema may
change the compilation result of the client (and similarly for the repl).
So, when running `yarn build`, it's best to build the schema first and
not the other way around.
=> Improve JSON schema definitions of base16 and base64 encoded strings.

server/app/Main.hs, server/cabal.project, server/modules/contra-tracers/CHANGELOG.md, server/modules/contra-tracers/LICENSE, server/modules/contra-tracers/README.md, server/modules/contra-tracers/contra-tracers.cabal, server/modules/contra-tracers/package.yaml, server/modules/contra-tracers/src/Data/Generics/Tracers.hs, server/modules/contra-tracers/src/Data/Severity.hs, server/ogmios.cabal, server/package.yaml, server/src/Ogmios.hs, server/src/Ogmios/App/Configuration.hs, server/src/Ogmios/App/Health.hs, server/src/Ogmios/App/Server.hs, server/src/Ogmios/App/Server/WebSocket.hs, server/src/Ogmios/Control/MonadLog.hs, server/src/Ogmios/Options.hs, server/src/Ogmios/Prelude.hs, server/stack.yaml, server/test/unit/Ogmios/App/Protocol/ChainSyncSpec.hs, server/test/unit/Ogmios/App/Protocol/StateQuerySpec.hs, server/test/unit/Ogmios/OptionsSpec.hs
Fixes #145 
```
$ ogmios --help
Provides a bridge between cardano-node and WebSocket clients. Ogmios translates
the existing CBOR-based Ouroboros mini-protocols into JSON-WSP-based protocols,
through WebSocket channels.
Usage: ogmios ((-v|--version) | --node-socket FILEPATH --node-config FILEPATH 
[--host IPv4] [--port TCP/PORT] [--timeout SECONDS] 
[--max-in-flight INT] 
[--log-level SEVERITY | [--log-level-health SEVERITY] 
[--log-level-metrics SEVERITY] 
[--log-level-websocket SEVERITY] [--log-level-server SEVERITY]
[--log-level-options SEVERITY]])
Ogmios - A JSON-WSP WebSocket adaptor for cardano-node
Available options:
-h,--help                Show this help text
-v,--version             Show the software current version and build revision.
--node-socket FILEPATH   Path to the node …
```
=> Make log minimum severity configurable per logging component.

.dockerignore, Dockerfile, server/app/Main.hs, server/ogmios.cabal, server/package.yaml, server/src/Ogmios.hs, server/src/Ogmios/App/Server/Http.hs, server/src/Ogmios/Options.hs
- :round_pushpin: **Rework Dockerfile to leverage Nix-produced static binary and caching.**
- :round_pushpin: **Add HEALTHCHECK to Docker images.**
- :round_pushpin: **Add 'health-check' command to easily perform a health check.**
In  essence, this is just making an HTTP request to Ogmios' health endpoint to look at the 'connectionStatus' field. While this is perfectly doable with wget or curl + jq or sed...
(a) It is more convenient to have a simple command for this, which directly conveys the intent.
(b) It doesn't require to make builds any more complex, in particular for containers which may not have curl, wget or even netcat available.
However, containers do already have 'ogmios' available, statically linked. So little manoeuver becomes very handy.
- :round_pushpin: **Use 'ogmios …
=> Rework Docker Images

scripts/cardano-node-ogmios.sh
When restarting the docker image, I was getting the following error
---------------------------------
{"severity":"Error","timestamp":"2022-01-11T12:39:45.998611484Z","thread":"179","message":{"WebSocket":{"ioException":"Network.Socket.connect: <socket: 19>: does not exist (No such file or directory)","tag":"WebSocketFailedToConnect"}},"version":"v5.0.0"}
---------------------------------
The /ipc/node.socket was being removed when restarting the cardanosolutions/cardano-node-ogmios docker container.
Changing this and rebuilding the image worked.
=> Fixing issue when restarting the docker image

CHANGELOG.md, clients/TypeScript/packages/client/test/ServerHealth.test.ts, docs/content/getting-started/monitoring.md, server/src/Ogmios/App/Health.hs, server/src/Ogmios/Data/Health.hs, server/test/unit/Ogmios/Data/HealthSpec.hs
Fixes #164
- :round_pushpin: **Extend 'Health' with current epoch number and slot within epoch.**
- :round_pushpin: **Get epoch number and slot in epoch from the time interpreter.**
- :round_pushpin: **Unit and smoke test 'currentEpoch' & 'slotInEra' in health**
From logs, on testnet:
```json
{
"severity": "Info",
"timestamp": "2022-01-24T14:56:58.61614791Z",
"thread": "16",
"message": {
"Health": {
"tag": "HealthTick",
"status": {
"startTime": "2022-01-24T14:56:38.537958011Z",
"lastKnownTip": {
"slot": 47729097,
"hash": "81d7b92d06ee966550153bbd41295a177b73ba9e7f59db770c57fcbeb0ba7217",
"blockNo": 3234906
},
"lastTipUpdate": "2022-01-24T14:56:58.615657341Z",
"networkSynchronization": 0.98813,
"currentEra": "Alonzo",
"metrics": {
"totalUnrouted": 0,
"totalMessages": 0,
"runtimeStats": { …
```
=> `currentEpoch` & `slotInEpoch` in health object

.gitmodules, README.md, clients/TypeScript/packages/client/src/TxSubmission/evaluateTx.ts, clients/TypeScript/packages/client/src/TxSubmission/evaluationErrors.ts, clients/TypeScript/packages/client/test/TxSubmission/TxSubmission.test.ts, clients/TypeScript/packages/schema/src/index.ts, docs/content/mini-protocols/local-tx-submission.md, docs/static/ogmios.wsp.json, server/modules/json-wsp/src/Codec/Json/Wsp.hs, server/ogmios.cabal, server/package.yaml, server/src/Ogmios/App/Protocol.hs, server/src/Ogmios/App/Protocol/TxSubmission.hs, server/src/Ogmios/Data/Json.hs, server/src/Ogmios/Data/Json/Orphans.hs, server/src/Ogmios/Data/Json/Prelude.hs, server/src/Ogmios/Data/Json/Query.hs, server/src/Ogmios/Data/Protocol.hs, server/src/Ogmios/Data/Protocol/TxSubmission.hs, server/test/unit/Ogmios/Data/JsonSpec.hs, server/test/unit/Test/Generators.hs
- :round_pushpin: **Introduce additional utxo set to the 'EvaluateTx' request message.**
The idea is to let clients provide an extra utxo set to complete the existing one from the network. This is useful for testing and playing around in a more reliable manner but is also useful to calculate execution units of chained transactions. It is fully optional.
- :round_pushpin: **Allow passing additional UTXO to the execution units evaluator.**
- :round_pushpin: **Write decoder for UTXO**
Property-tested in roundtrips against the UTXO encoders, for which there already exists a slew of tests ensuring they match the JSON-schema. This gives guarantees that the JSON decoders are following the right JSON-schema and works accordingly.
- :round_pushpin: **Fix type-reflection assertions not picking up …
=> EvaluateTx: allows user-specified additional UTXO set

clients/TypeScript/packages/client/src/IsomorphicWebSocket.ts
Could just skip the second `protocols` argument of `WebSocket` constructor, which accepts a `string` or `string[]`. Here are [details of the value](https://javascript.info/websocket#extensions-and-subprotocols).
=> Skip options for browser WebSocket()

clients/TypeScript/.eslintrc.js, clients/TypeScript/packages/client/package.json, clients/TypeScript/packages/client/src/TxSubmission/TxSubmissionClient.ts, clients/TypeScript/packages/client/src/TxSubmission/evaluateTx.ts, clients/TypeScript/packages/client/src/TxSubmission/submitTx.ts, clients/TypeScript/packages/client/src/util.ts, clients/TypeScript/packages/client/test/TxSubmission/TxSubmission.test.ts, clients/TypeScript/packages/client/test/util.test.ts, clients/TypeScript/yarn.lock
Fix #197 
---
- :round_pushpin: **Add TypeScript util to convert an event emitter into an asynchronous generator.**
In cases where (a) we expect only one event in response to some other effect and (b) events to come in the same order as the requests, then it becomes useful to simply treat some event source as a stream of values yielded by a generator. Not only it is useful, but it allows to make the consuming code relatively simple as we can now fire some event and wait synchronously on the response.
- :round_pushpin: **Rework submitTx to use the new util for waiting on server responses.**
Now, we only need to have a single event listener for the whole submission client. Many requests can be fired asynchronously and handled in due time; behind the scene the server still process them one …
=> Avoid setting multiple event handlers for each evaluateTx/submitTx calls. 

.github/workflows/continuous-integration.yaml, Dockerfile, docker-compose.yml
The `cardano-node` version bump was missed in a few places
=> fix: cardano-node version in Docker and CI

clients/TypeScript/packages/client/src/util.ts
The helpers to determine what era the protocol parameters belong to were "out-dated".
1. Existing ones (`isShelleyProtocolParameters` and `isAlonzoProtocolParameters`) were hard-to-use, as they didn't accept the new `ProtocolParametersBabbage` type
2. And the function `isBabbageProtocolParameters` was missing.
This PR should fix both of these issues.
=> Update protocol parameter helpers in TypeScript client

clients/TypeScript/packages/client/src/errors/UnknownResultError.ts
Submitting an invalidly encoded tx payload throws this error, which currently requires string manipulation prior to JSON parsing.
```
{"type":"jsonwsp/fault","version":"1.0","servicename":"ogmios","fault":{"code":"client","string":"Invalid request: failed to decode payload from base64 or base16."},"reflection":null} is an unknown result
```
The concatenated description is superfluous given the error name already sets the context
=> Remove superfluous string concatenation in TS client UnknownResultError

docs/content/mini-protocols/local-state-query.md
Fixes #247 
Typo in the ogmios state query documentation
https://ogmios.dev/mini-protocols/local-state-query/#delegationsandrewards
=> fix: Typo in the ogmios document

.github/workflows/package.yaml
This will trigger a build for both amd64 and arm64. The result is a multi-platform image that works on for both CPU architectures.
refs #250
=> Add arm64 as platform to ogmios image build

server/ogmios.cabal, server/package.yaml, server/src/Ogmios/App/Metrics/Prometheus.hs, server/src/Ogmios/App/Server/Http.hs, server/src/Ogmios/Data/Metrics/Prometheus.hs
This patch adds `/metrics` route which exports metrics in Prometheus format (using encoding from `prometheus` library).
Sample output:
```bash
$ curl localhost:1337/metrics
active_connections  0.0
connected  1.0
cpu_time  3841629783
current_epoch  363
current_heap_size  390.0
gc_cpu_time  3142668337
max_heap_size  433.0
network_synchronization  0.99999
session_duration_max  0.0
session_duration_mean  0.0
session_duration_mix  0.0
slot_in_epoch  150361
tip_block  7756720
tip_slot  71603161
total_connections  0
total_messages  0
total_unrouted  0
```
Note that connection status of `Connected` is encoded as `connected 1` and `Disconnected` as `connected 0`.
For a special case when tip is at genesis there is a `tip_at_genesis 1` metric reported until tip updates and `tip_block` and `tip_slot` …
=>  Health over Prometheus metrics

clients/TypeScript/packages/client/src/util.ts, clients/TypeScript/packages/client/test/util.test.ts
`Value` without assets comes as `{coins:n}` instead of `{coins:n, assets:{}}` from the server, which results in `Lovelace` not being sanitized.
=> Fix 'sanitize' to support Value without 'assets'

server/cabal.project
Hey :wave: Can we add this hash after the recent dependency changes? :pray: Otherwise our Hydra rejects the build in pure mode. Thank you!
Related to #341
=> Add a missing source-repository-package hash

.github/workflows/continuous-integration.yaml
SanchoNet is a public network that will be supported for some time. It would be great to have pre-built images while this network is live
=> Add SanchoNet variant to Dockerhub builds

server/cabal.project
The one listed in the project appears to be incorrect and not match the revision.
=> Update sha256 for ouroboros-network

clients/TypeScript/packages/client/src/TransactionSubmission/Client.ts
When sending two requests to ogmios, e.g. `protocolParameters` and `evaluateTransaction`, response for `protocolParameters` is matched in `matchEvaluateTransaction` because `'method' in json.id` is false.
There is a top-level `method` field as defined in https://ogmios.dev/api/#operation-publish-/?EvaluateTransaction
=> Fix extracting method from response

CHANGELOG.md, README.md, docs/content/_index.md, docs/content/faq/_index.md, docs/content/getting-started/docker.md, docs/content/mini-protocols/_index.md, docs/content/mini-protocols/local-tx-submission.md
* Update docs to point to new intersectMBO links.
* Update cardano-node repo to cardano-cli repo.
Fixes #369
=> Docs: Update links to new intersectMBO repo

server/cabal.project
I do patch it in our tree, so it's not a blocker, but it might be useful to contribute back. :)
=> Add a missing `sha256` for Haskell.nix compatibility

server/ogmios.cabal, server/package.yaml, server/src/Ogmios/App/Protocol/TxSubmission.hs, server/src/Ogmios/App/Server/WebSocket.hs, server/src/Ogmios/Data/EraTranslation.hs, server/src/Ogmios/Data/Protocol/TxSubmission.hs
Closes #375.
- :round_pushpin: **Augment ExecutionUnitsEvaluator with mempool info**
This shall make the mempool available to the evaluator. The background
mempool client running here is very simple, it drains all the
transaction from the mempool and store them in a TMVar, then wait for
a new snapshot.
We use a TMVar and not a TVar here to ensure that the full list is
only available when we have drained all transactions (so that a
concurrent reader cannot access a partially fetched mempool).
We also provide a way to invalidate the mempool, which is potentially
hazardous if used recklessly. But, the intent is to invalidate the
mempool after every transaction submission so that there's no race
condition for clients that would be evaluating then submitting many
transactions. This will cause …
=> Evaluate with mempool

server/cabal.project
v6.2 branch is still incompatible with haskell.nix because it lacks this fix.
=> Apply #378 to v6.2

docs/content/mini-protocols/local-tx-monitor.md
Update local-tx-monitor example
=> Update mempool example to v6.x

server/src/Ogmios/App/Protocol/TxSubmission.hs
This simplifies downstream logic, since we can just provide the UTXOs we have, and not worry about whether they've been included in the ledger by now or not.
(Disclaimer: I'm terrified of getting a haskell dev environment up, so this hasn't been tested, and might need imports tweaked)
=> Only return the OverlappingAdditionalUtxo error if the provided UTXO actually differs from the one in the ledger

clients/TypeScript/packages/client/src/LedgerStateQuery/Client.ts
The parameter was introduced here: https://github.com/CardanoSolutions/ogmios/commit/37af3a8a138a20f2f2fed7cdbe87d2836de461bb#diff-b15b783a10f9fc2b73f782b921d2d3a0d702d8c677e2dbdfa8377d136291f8a9L12
But it was not properly propagated in the interface, so it could not be used from outside ogmios-client
=> Add stakePools parameter to stakePools query

clients/TypeScript/packages/client/src/util.ts
Resolves the issue `raw.replace is not a function` that seems to randomly occur during indexing. In some cases, `raw` is a buffer, which needs converted to a string before calling the `.replace(...)`
=> Convert raw to string
